version: '3'

services:
    app:
        container_name: app
        build: .
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - 3000:3000
            - 9229:9229
        links:
            - db
        command: yarn start
    db:
        container_name: db
        image: mongo
        volumes:
            - ./data:/data/db
        ports:
            - 24014:27017
